// Auto-generated by scripts/sync-vpc-bindings.mjs from wrangler.jsonc.
// Do not edit by hand — your changes will be overwritten on the next
// `npm run build`. To add or remove a binding, edit wrangler.jsonc.

import type { VpcBinding } from "./vpc";

export const VPC_BINDINGS: VpcBinding[] = [
  {
    "binding": "RESPONDY",
    "type": "service",
    "id": "019e3d8b-f4d6-7471-b0bb-a7a52687cd78"
  }
];
